services:
  dashboard:
    build: .
    image: guzus/llm-mafia-game-dashboard:latest
    platform: linux/amd64
    ports:
      - "5001:5001"
    volumes:
      - ./firebase_credentials.json:/app/firebase_credentials.json
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    command: uv run src/dashboard.py --port 5001

  simulation:
    build: .
    image: guzus/llm-mafia-game-simulation:latest
    platform: linux/amd64
    volumes:
      - ./firebase_credentials.json:/app/firebase_credentials.json
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - NUM_GAMES=${NUM_GAMES}
    command: uv run src/simulate.py
